#!/usr/bin/env python3
"""
verificar_schema.py
--------------------
Verifica se o schema REAL do banco (Supabase/Postgres) bate com o schema
ESPERADO pelo projeto e tenta corrigir automaticamente as diferenças.

Uso:
    python -m analytics.verificar_schema
(rodar da raiz do projeto, com o .env carregado)
"""

import os
import re
import sys
from typing import Dict, Set

from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError


def load_env_file(path: str = ".env") -> None:
    if not os.path.exists(path):
        return

    with open(path, "r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("export "):
                line = line[7:].strip()
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"\'')
            if key and value:
                os.environ.setdefault(key, value)


load_env_file()

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    print("ERRO: DATABASE_URL não encontrada no .env nem nas variáveis de ambiente")
    sys.exit(1)

EXPECTED_SCHEMA = {
    "game_rounds": {
        "columns": {
            "id": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "round_id": "TEXT NOT NULL",
            "multiplier": "NUMERIC(12, 2)",
            "timestamp": "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "round_timestamp": "TIMESTAMPTZ",
            "crash_point": "NUMERIC(12, 2)",
            "raw_payload": "TEXT",
            "source": "TEXT",
            "created_at": "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP",
        },
        "unique_columns": {"round_id"},
    },
    "collector_runs": {
        "columns": {
            "id": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "status": "TEXT NOT NULL DEFAULT 'pending'",
            "rounds_inserted": "INTEGER NOT NULL DEFAULT 0",
            "error_message": "TEXT",
            "started_at": "TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP",
            "finished_at": "TIMESTAMPTZ",
        },
        "unique_columns": set(),
    },
}

engine = create_engine(DATABASE_URL, pool_pre_ping=True)


def get_actual_columns(conn, table: str) -> Set[str]:
    rows = conn.execute(
        text("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = :t
        """),
        {"t": table},
    ).fetchall()
    return {row[0] for row in rows}


def get_unique_columns(conn, table: str) -> Set[str]:
    rows = conn.execute(
        text("""
            SELECT a.attname
            FROM pg_constraint c
            JOIN unnest(c.conkey) AS colnum ON true
            JOIN pg_attribute a
              ON a.attrelid = c.conrelid AND a.attnum = colnum
            WHERE c.conrelid = to_regclass(:t) AND c.contype IN ('u', 'p')
        """),
        {"t": f"public.{table}"},
    ).fetchall()
    return {row[0] for row in rows}


def table_exists(conn, table: str) -> bool:
    row = conn.execute(
        text("""
            SELECT to_regclass(:t) IS NOT NULL AS exists
        """),
        {"t": f"public.{table}"},
    ).scalar()
    return bool(row)


def ensure_schema(conn, table: str, expected: Dict[str, object]) -> None:
    columns = expected["columns"]
    unique_columns = expected["unique_columns"]

    if not table_exists(conn, table):
        column_sql = ", ".join(f"{name} {definition}" for name, definition in columns.items())
        conn.execute(text(f"CREATE TABLE public.{table} ({column_sql});"))
        print(f"[{table}] tabela criada com sucesso.")
        return

    actual_columns = get_actual_columns(conn, table)
    for column_name, definition in columns.items():
        if column_name in actual_columns:
            continue
        try:
            conn.execute(text(f"ALTER TABLE public.{table} ADD COLUMN IF NOT EXISTS {column_name} {definition};"))
            print(f"[{table}] coluna adicionada: {column_name}")
        except SQLAlchemyError as exc:
            print(f"[{table}] não foi possível adicionar a coluna {column_name}: {exc}")
            raise

    for unique_column in sorted(unique_columns):
        if unique_column in get_unique_columns(conn, table):
            continue
        constraint_name = f"{table}_{unique_column}_key"
        conn.execute(
            text(f"""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint c
                        JOIN pg_attribute a
                          ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
                        WHERE c.conrelid = 'public.{table}'::regclass
                          AND c.contype IN ('u', 'p')
                          AND a.attname = '{unique_column}'
                    ) THEN
                        ALTER TABLE public.{table}
                        ADD CONSTRAINT {constraint_name} UNIQUE ({unique_column});
                    END IF;
                END $$;
            """)
        )
        print(f"[{table}] constraint UNIQUE adicionada para: {unique_column}")


def main() -> int:
    problems = []

    try:
        with engine.begin() as conn:
            for table, expected in EXPECTED_SCHEMA.items():
                ensure_schema(conn, table, expected)

            for table, expected in EXPECTED_SCHEMA.items():
                actual_columns = get_actual_columns(conn, table)
                if not actual_columns:
                    problems.append(f"[{table}] TABELA NÃO ENCONTRADA no banco.")
                    continue

                missing = set(expected["columns"].keys()) - actual_columns
                extra = actual_columns - set(expected["columns"].keys())
                if missing:
                    problems.append(f"[{table}] colunas esperadas mas AUSENTES no banco: {sorted(missing)}")
                if extra:
                    print(f"[{table}] aviso: colunas no banco não listadas em EXPECTED_SCHEMA: {sorted(extra)}")

                actual_unique = get_unique_columns(conn, table)
                missing_unique = set(expected["unique_columns"]) - actual_unique
                if missing_unique:
                    problems.append(
                        f"[{table}] colunas SEM constraint UNIQUE/PK necessárias para ON CONFLICT: {sorted(missing_unique)}"
                    )
    except SQLAlchemyError as exc:
        print(f"ERRO ao ajustar o schema: {exc}")
        return 1

    print("\n" + "=" * 60)
    if problems:
        print(f"❌ {len(problems)} problema(s) encontrado(s):\n")
        for problem in problems:
            print(" -", problem)
        print(
            "\nDicas de correção:\n"
            "  - Coluna ausente: a rotina tentou criar/alterar o schema automaticamente.\n"
            "  - Falta de UNIQUE: a rotina tentou adicionar a constraint UNIQUE automaticamente."
        )
        return 1

    print("✅ Schema real bate com o EXPECTED_SCHEMA. Pipeline liberado para rodar.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
